version: "3.3"
services:
  db:
    image: "mysql:5.7"
    container_name: "todo-app-db"
    ports:
      - "3306:3306"
    volumes:
      - "./database.sql:/docker-entrypoint-initdb.d/database.sql"
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'